version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started
      - ./build.sh
      - docker tag spring-demo $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/spring-demo:latest
      - docker tag code-with-quarkus $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/code-with-quarkus:latest
  post_build:
    commands:
      - echo Build complete
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/spring-demo:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/code-with-quarkus:latest